### ISSUE TITLE
Estimation of EKF Localizer Parameters

### ISSUE THREAD

**Issue by yvzksgl** [tier4/CalibrationTools#118]
Hello,

I have a question about how to estimate ```ekf_localizer``` parameters with using ```deviation_estimator``` tool. Readme says: 
```The node also estimates the standard deviation of velocity and yaw rate. This can be used as a parameter in ekf_localizer.```
But the node's outputs are imu_corrector.param.yaml and vehicle_velocity_converter.param.yaml files' parameters. Can I transform 
```
velocity_stddev_xx
angular_velocity_stddev_xx
angular_velocity_stddev_yy
angular_velocity_stddev_zz
```
to
```
proc_stddev_yaw_c
```
In short i want to use deviation_estimator tool to optimize ekf_localizer parameters, but i cannot find a way to do that.

**Comment by knzo25** [comment]
@kminoda :pray:

**Comment by kminoda** [comment]
`proc_stddev_yaw_c` is a process noise and not observation noise. It is irrelevant to the sensors, but to the kinematics model. 
The estimated covariance for IMU and velocity should be reflected in `imu_corrector` and `vehicle_velocity_converter`, respectively. Those would be eventually merged into `/localization/twist_estimator/twist_with_covariance` with the covariance reflected.

So the answer is: Please reflect those estimated parameters not in `ekf_localizer` but to `imu_corrector` and `vehicle_velocity_converter`.

**Comment by yvzksgl** [comment]
İ understand thank yo for your response. Have a nice week.
