### ISSUE TITLE
How can I receive extrinsic_calibration service?

### ISSUE THREAD

**Issue by enddl3224** [tier4/CalibrationTools#181]
Hi, I'm trying to use camera-lidar calibration tool using `tag_based_pnp_calibrator.launch.xml`.
and I want to check the values(initial_reprojection_error, current_reprojection_error, filtered_reprojection_error).

If I receive `extrinsic_calibration` service,
then `request_received_ = true;` 
I think I can also get the above values as well.

How can I receive `extrinsic_calibration` service?

I'm attaching some pictures.

- Code
![Screenshot from 2024-07-23 16-18-17](https://github.com/user-attachments/assets/d2c939a9-0fe0-404a-b33d-1720158325b4)
![Screenshot from 2024-07-23 15-54-53](https://github.com/user-attachments/assets/beb511b9-05b0-4050-90f1-4f86b58dc24f)

- Image view
![Screenshot from 2024-07-23 15-55-12](https://github.com/user-attachments/assets/5828065a-12f8-4772-8690-78bf763f2af1)

- TF tree
![Screenshot from 2024-07-23 15-56-43](https://github.com/user-attachments/assets/7b15a202-7852-4a01-92f1-045f51a97ee3)

- node, topic info
![Screenshot from 2024-07-23 16-02-24](https://github.com/user-attachments/assets/0c067ef5-d0e8-4d93-9e64-6914cbb4ff51)
![Screenshot from 2024-07-23 16-01-22](https://github.com/user-attachments/assets/168ed0cb-01fb-4854-92f7-350199ded875)
![Screenshot from 2024-07-23 16-00-04](https://github.com/user-attachments/assets/1798a580-e2ee-4953-85bd-a6827892ab7b)
![Screenshot from 2024-07-23 15-59-47](https://github.com/user-attachments/assets/e3d6da75-40da-461b-9589-ac5f6569f79b)

Thank you.

**Comment by knzo25** [comment]
@enddl3224 
Although you provided a lot of data I don't fully understand.
Are you using the calibrator manager? If not, you can always send the service manually

**Comment by enddl3224** [comment]
Thank you for comment!
I'm using the calibrator manager(sensor_calibration_manager).
But could you tell me how can I send the service manually?
I guess I didn't send the service.

**Comment by knzo25** [comment]
Please check if the service name from both the server and the client coincide. When creating launchers, it is the most common mistake, and that is why newer versions should allow to use the tools without writing launchers (the so called default project).
To send services manually just type `ros2 service call service_name` and then use autocomplete to deduce the type and contents. Sadly, that is out of the scope of the support we can do as it falls outside the intended use of these tools and correspond to the integration work of users

**Comment by enddl3224** [comment]
Thank you so much! I'll try it.

**Comment by knzo25** [comment]
@enddl3224 
If there are no updated on this, I will be closing this in about one week
