### ISSUE TITLE
[mapping_based_calibrator] Code Bug?

### ISSUE THREAD

**Issue by b06902126** [tier4/CalibrationTools#209]
Hi, I'm using mapping_based_calibrator and tracing the code to see how you implement. Then, I'm confused in CalibrationMapper::checkKeyframeLost. 

![Screenshot from 2024-11-08 12-12-11](https://github.com/user-attachments/assets/19e76c51-ae79-43ab-a5ec-9f23fca52a67)

It seems that you OR the same condition in if? Or there is a misunderstanding?

**Comment by knzo25** [comment]
@b06902126 
Thanks ! It certainly looks like a bug. Will check it later and send a PR :pray:

**Comment by knzo25** [comment]
Send a PR here: https://github.com/tier4/CalibrationTools/pull/211
Once that is merged, I will close this issue :pray:

**Comment by knzo25** [comment]
The PR was merged so I will be closing this issue
