### ISSUE TITLE
Dimensions of boards

### ISSUE THREAD

**Issue by bariskapaligoz** [tier4/CalibrationTools#84]
Hi, i want to test your tag based calibration tool. I have a few questions about dimensions of your boards.

![image](https://user-images.githubusercontent.com/88723631/217794232-5f001295-3828-42bc-9edc-a6a5ef64506e.png)

I am wondering lengths of fiducial marker(Yellow square), black edge and outermost white edge. The reason I ask is because I want the board we will use to be compatible with the default parameters that you define in both apriltag and lidartag.

Thank you in advance.

**Comment by knzo25** [comment]
Hi, our boards are 0.8m side-to-side, making each "cell" you see in the image to be 10cm x 10cm.
Let us know if there is anything we can help you with !

**Comment by bariskapaligoz** [comment]
Thank you very much for the quick help!
